// This file is auto-generated by scripts/generate-types.ts
// Do not edit manually. Run `pnpm generate:types` to update.

// Example types (replace with output from Supabase CLI or introspection)
export type Platform = 'neothink' | 'ascenders' | 'immortals' | 'neothinkers'

export interface Profile {
  id: string
  user_id: string
  username: string
  full_name: string | null
  avatar_url: string | null
  platform: Platform
  created_at: string
  updated_at: string
}

export interface PrivacySettings {
  id: string
  user_id: string
  email_visibility: 'public' | 'private' | 'members'
  profile_visibility: 'public' | 'private' | 'members'
  activity_visibility: 'public' | 'private' | 'members'
  created_at: string
  updated_at: string
}

export interface Subscription {
  id: string
  user_id: string
  status: 'active' | 'canceled' | 'past_due'
  current_period_start: string
  current_period_end: string
  cancel_at_period_end: boolean
  created_at: string
  updated_at: string
}

export interface Course {
  id: string
  title: string
  description: string
  platform: Platform
  status: 'draft' | 'published' | 'archived'
  created_at: string
  updated_at: string
}

export interface Lesson {
  id: string
  course_id: string
  title: string
  content: string
  order: number
  created_at: string
  updated_at: string
}

export interface Progress {
  id: string
  user_id: string
  lesson_id: string
  completed: boolean
  created_at: string
  updated_at: string
}

export interface ForumPost {
  id: string
  user_id: string
  title: string
  content: string
  platform: Platform
  status: 'published' | 'archived'
  created_at: string
  updated_at: string
}
