// This file is auto-generated by the Supabase CLI. Do not edit manually.
// To regenerate, run:
//   SUPABASE_PROJECT_ID=your-project-id supabase gen types typescript --project-id $SUPABASE_PROJECT_ID --schema public > index.ts

// Placeholder: Run the above command to generate types from your Supabase project.

export type Database = unknown;
