name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Type Check
        run: pnpm type-check

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Run E2E Tests
        run: pnpm e2e
      - name: Audit Dependencies
        run: pnpm audit --audit-level=moderate || true

# This workflow is governed by the Neothink DAO and is not MIT licensed.
# All rights and governance are reserved by the Neothink DAO. 